### ISSUE TITLE
Reduce is not defined?

### ISSUE THREAD

**Issue by jindongwang** [STO-OTZ/my_gcForest#1]
![qq 20170304101522](https://cloud.githubusercontent.com/assets/6158206/23575144/818ea00c-00c3-11e7-86d4-dd9b4b51e590.png)

**Comment by STO-OTZ** [comment]
I'm using python2.7, reduce is a built-in function.

Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> reduce
<built-in function reduce>

**Comment by zhhezhhe** [comment]
from functools import reduce

**Comment by STO-OTZ** [comment]
谢谢，已经加上了。
